version: '3.0'

services:
  main:
    container_name: ura_remont_server
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run start
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: ura_remont_pd_data
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
